import { msg } from '@lingui/core/macro';
import {
  FieldMetadataType,
  RelationOnDeleteAction,
} from 'twenty-shared/types';

import { RelationType } from 'src/engine/metadata-modules/field-metadata/interfaces/relation-type.interface';
import { Relation } from 'src/engine/workspace-manager/workspace-sync-metadata/interfaces/relation.interface';

import { BaseWorkspaceEntity } from 'src/engine/twenty-orm/base.workspace-entity';
import { WorkspaceEntity } from 'src/engine/twenty-orm/decorators/workspace-entity.decorator';
import { WorkspaceField } from 'src/engine/twenty-orm/decorators/workspace-field.decorator';
import { WorkspaceIsNullable } from 'src/engine/twenty-orm/decorators/workspace-is-nullable.decorator';
import { WorkspaceRelation } from 'src/engine/twenty-orm/decorators/workspace-relation.decorator';
import { WorkspaceJoinColumn } from 'src/engine/twenty-orm/decorators/workspace-join-column.decorator';
import { WorkspaceIsSystem } from 'src/engine/twenty-orm/decorators/workspace-is-system.decorator';
import { STANDARD_OBJECT_IDS } from 'src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-ids';
import { ProspectLeadWorkspaceEntity } from 'src/modules/marketing-ai-agent/standard-objects/prospect-lead.workspace-entity';
import { OutreachMessageWorkspaceEntity } from 'src/modules/marketing-ai-agent/standard-objects/outreach-message.workspace-entity';

export const MARKETING_CAMPAIGN_STANDARD_FIELD_IDS = {
  name: '20000000-0000-0000-0000-000000000001',
  description: '20000000-0000-0000-0000-000000000002',
  status: '20000000-0000-0000-0000-000000000003',
  targetAudience: '20000000-0000-0000-0000-000000000004',
  aiGeneratedPlan: '20000000-0000-0000-0000-000000000005',
  startDate: '20000000-0000-0000-0000-000000000006',
  endDate: '20000000-0000-0000-0000-000000000007',
  budget: '20000000-0000-0000-0000-000000000008',
  performance: '20000000-0000-0000-0000-000000000009',
};

export type CampaignStatus = 'draft' | 'active' | 'paused' | 'completed';

@WorkspaceEntity({
  standardId: '20000000-0000-0000-0000-000000000000',
  namePlural: 'marketingCampaigns',
  labelSingular: msg`Marketing Campaign`,
  labelPlural: msg`Marketing Campaigns`,
  description: msg`AI-powered marketing campaigns for customer outreach`,
  icon: 'IconSpeakerphone',
  labelIdentifierStandardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.name,
})
export class MarketingCampaignWorkspaceEntity extends BaseWorkspaceEntity {
  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.name,
    type: FieldMetadataType.TEXT,
    label: msg`Name`,
    description: msg`Campaign name`,
    icon: 'IconTag',
  })
  name: string;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.description,
    type: FieldMetadataType.TEXT,
    label: msg`Description`,
    description: msg`Campaign description`,
    icon: 'IconFileText',
  })
  @WorkspaceIsNullable()
  description: string | null;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.status,
    type: FieldMetadataType.SELECT,
    label: msg`Status`,
    description: msg`Campaign status`,
    icon: 'IconProgress',
    options: [
      { value: 'draft', label: 'Draft', position: 0, color: 'gray' },
      { value: 'active', label: 'Active', position: 1, color: 'green' },
      { value: 'paused', label: 'Paused', position: 2, color: 'yellow' },
      { value: 'completed', label: 'Completed', position: 3, color: 'blue' },
    ],
    defaultValue: "'draft'",
  })
  status: CampaignStatus;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.targetAudience,
    type: FieldMetadataType.TEXT,
    label: msg`Target Audience`,
    description: msg`Description of the target audience`,
    icon: 'IconUsers',
  })
  @WorkspaceIsNullable()
  targetAudience: string | null;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.aiGeneratedPlan,
    type: FieldMetadataType.TEXT,
    label: msg`AI Generated Plan`,
    description: msg`Marketing plan generated by AI`,
    icon: 'IconRobot',
  })
  @WorkspaceIsNullable()
  aiGeneratedPlan: string | null;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.startDate,
    type: FieldMetadataType.DATE_TIME,
    label: msg`Start Date`,
    description: msg`Campaign start date`,
    icon: 'IconCalendar',
  })
  @WorkspaceIsNullable()
  startDate: Date | null;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.endDate,
    type: FieldMetadataType.DATE_TIME,
    label: msg`End Date`,
    description: msg`Campaign end date`,
    icon: 'IconCalendar',
  })
  @WorkspaceIsNullable()
  endDate: Date | null;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.budget,
    type: FieldMetadataType.NUMBER,
    label: msg`Budget`,
    description: msg`Campaign budget`,
    icon: 'IconCurrencyDollar',
  })
  @WorkspaceIsNullable()
  budget: number | null;

  @WorkspaceField({
    standardId: MARKETING_CAMPAIGN_STANDARD_FIELD_IDS.performance,
    type: FieldMetadataType.RAW_JSON,
    label: msg`Performance Metrics`,
    description: msg`Campaign performance metrics`,
    icon: 'IconChartBar',
  })
  @WorkspaceIsNullable()
  @WorkspaceIsSystem()
  performance: Record<string, any> | null;

  // Relations
  @WorkspaceRelation({
    standardId: '20000000-0000-0000-0000-00000000000a',
    type: RelationType.ONE_TO_MANY,
    label: msg`Prospect Leads`,
    description: msg`Prospect leads for this campaign`,
    icon: 'IconUserPlus',
    inverseSideTarget: () => ProspectLeadWorkspaceEntity,
    onDelete: RelationOnDeleteAction.CASCADE,
  })
  prospectLeads: Relation<ProspectLeadWorkspaceEntity[]>;

  @WorkspaceRelation({
    standardId: '20000000-0000-0000-0000-00000000000b',
    type: RelationType.ONE_TO_MANY,
    label: msg`Outreach Messages`,
    description: msg`Outreach messages sent in this campaign`,
    icon: 'IconMail',
    inverseSideTarget: () => OutreachMessageWorkspaceEntity,
    onDelete: RelationOnDeleteAction.CASCADE,
  })
  outreachMessages: Relation<OutreachMessageWorkspaceEntity[]>;
}
